name: Deploy production
on: 
  push:
    branches: [ main ]

jobs:
  canceling-previous-deploys:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancelling
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-and-deploy-to-google:
    environment: production
    needs: [ canceling-previous-deploys ]
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: Google Auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}
          token_format: 'access_token'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io' # or REGION-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      
      - run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io
      
      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }}:${{  github.sha }} .
          docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }}:${{  github.sha }}
      
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }} \
            --region ${{ secrets.REGION }} \
            --image gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }}:${{  github.sha }} \
            --platform "managed" \
            --quiet
      