name: Deploy production
on: 
  push:
    branches: [ main ]

jobs:
  canceling-previous-deploys:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancelling
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build-and-deploy-to-google:
    environment: production
    needs: [ canceling-previous-deploys ]
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: Google Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }}:${{  github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }}:${{  github.sha }}
      
      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }} \
            --region ${{ secrets.REGION }} \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GOOGLE_CLOUD_RUN_SERVICE }}:${{  github.sha }} \
            --platform "managed" \
            --quiet
      